//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace egitimportali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitim
    {
        public string egitimId { get; set; }
        public string egitimAd { get; set; }
        public string egitimDersId { get; set; }
    
        public virtual Ders Ders { get; set; }
    }
}
